[metadata]
name = slayton
version = 1.0.0
description = A demonstration of thermuclear anthill removal.
author = Robert J. Hansen
author_email = rob@hansen.engineering
license = Apache-2.0
license_files = LICENSE-2.0.txt
long_description = file: README.rst
long_description_content_type = text/x-rst; charset=UTF-8
url = https://github.com/rjhansen/slayton
platforms = any
classifiers =
    Development Status :: 4 - Beta
    Programming Language :: Python

[options]
zip_safe = False
packages = find_namespace:
include_package_data = True
package_dir =
    =src
python_requires = >=3.12
install_requires =
    antlr4-python3-runtime > 4.10

[options.packages.find]
where = src
exclude =
    tests

[options.extras_require]

testing =
    setuptools
    pytest
    pytest-cov

[options.entry_points]

[tool:pytest]
addopts =
    --cov slayton --cov-report term-missing
    --verbose
norecursedirs =
    dist
    build
    .tox
testpaths = tests

[devpi:upload]
no_vcs = 1
formats = bdist_wheel

[flake8]
max_line_length = 88
extend_ignore = E203, W503
exclude =
    .tox
    build
    dist
    .eggs
    docs/conf.py

[pyscaffold]
version = 4.6
package = slayton
